# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Rajat Singla
email: rajatrs5054@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi there, Welcome to rajat's blog. You will find blogs here on ror,emberjs,deployment
  ,some cool programming stuff and my new findings.
  Currently i am working on soldier2ndlife(a product of navyug) a portal to help retired veterans.To get my attention send me a paradox. :)
baseurl: "http://rajatsingla.in" # the subpath of your site, e.g. /blog
url: "http://rajatsingla.in" # the base hostname & protocol for your site
twitter_username: rajatrs5054
github_username:  rajatsingla

# Build settings
markdown: kramdown
excerpt_separator: <!--more-->
